#! /usr/bin/env python
#-*-coding: utf-8-*-


SERVER_IP_ADDRESS       = "192.168.0.12"
SERVER_PORT             = 13000

SERVER_MAX_CONNECTIONS  = 5

SERVER_DATA_BUF_SIZE    = 1024

CLIENT_DATA_BUF_SIZE    = SERVER_DATA_BUF_SIZE


PACKAGE_STD_SIZE        = 10