#! /usr/bin/env python
#-*-coding: utf-8-*-


SERVER_IP_ADDRESS       = "127.0.0.1"
SERVER_PORT             = 13000

SERVER_MAX_CONNECTIONS  = 10

SERVER_DATA_BUF_SIZE    = 4096

CLIENT_DATA_BUF_SIZE    = SERVER_DATA_BUF_SIZE
